const cityToProvince = {
    "Karachi": "Sindh",
    "Lahore": "Punjab",
    "Islamabad": "Islamabad Capital Territory",
    "Rawalpindi": "Punjab",
    "Faisalabad": "Punjab",
    "Peshawar": "Khyber Pakhtunkhwa",
    "Quetta": "Balochistan",
    "Multan": "Punjab",
    "Gujranwala": "Punjab",
    "Sialkot": "Punjab",
    "Hyderabad": "Sindh",
    "Sukkur": "Sindh",
    "Bahawalpur": "Punjab",
    "Abbottabad": "Khyber Pakhtunkhwa",
    "Attock": "Punjab",
    "Bannu": "Khyber Pakhtunkhwa",
    "Bhakkar": "Punjab",
    "Chakwal": "Punjab",
    "Chaman": "Balochistan",
    "Chiniot": "Punjab",
    "Dera Ghazi Khan": "Punjab",
    "Dera Ismail Khan": "Khyber Pakhtunkhwa",
    "Gojra": "Punjab",
    "Gwadar": "Balochistan",
    "Hafizabad": "Punjab",
    "Jhang": "Punjab",
    "Jhelum": "Punjab",
    "Kasur": "Punjab",
    "Kohat": "Khyber Pakhtunkhwa",
    "Larkana": "Sindh",
    "Mandi Bahauddin": "Punjab",
    "Mardan": "Khyber Pakhtunkhwa",
    "Mirpur (AJK)": "Azad Jammu & Kashmir",
    "Mirpur Khas": "Sindh",
    "Muzaffargarh": "Punjab",
    "Muzaffarabad (AJK)": "Azad Jammu & Kashmir",
    "Nawabshah": "Sindh",
    "Nowshera": "Khyber Pakhtunkhwa",
    "Okara": "Punjab",
    "Rahim Yar Khan": "Punjab",
    "Sahiwal": "Punjab",
    "Sheikhupura": "Punjab",
    "Swabi": "Khyber Pakhtunkhwa",
    "Swat (Mingora)": "Khyber Pakhtunkhwa",
    "Tando Adam": "Sindh",
    "Turbat": "Balochistan",
    "Vehari": "Punjab",
    "Wah Cantt": "Punjab",
    "Abdul Hakim": "Punjab",
    "Ahmadpur East": "Punjab",
    "Akora": "Khyber Pakhtunkhwa",
    "Allahabad": "Punjab",
    "Arandu": "Khyber Pakhtunkhwa",
    "Arifwala": "Punjab",
    "Atharan Hazari": "Punjab",
    "Attock Khurd": "Punjab",
    "Awan Patti": "Punjab",
    "Ayun": "Khyber Pakhtunkhwa",
    "Badin": "Sindh",
    "Badrashni": "Punjab",
    "Bagh": "Azad Jammu & Kashmir",
    "Bagu Na Mohra": "Punjab",
    "Bahawalnagar": "Punjab",
    "Bahrain": "Balochistan",
    "Baltit": "Gilgit-Baltistan",
    "Bandhi": "Punjab",
    "Basla": "Punjab",
    "Bat Khela": "Khyber Pakhtunkhwa",
    "Batgram": "Khyber Pakhtunkhwa",
    "Bela": "Balochistan",
    "Bhalwal": "Punjab",
    "Bhawana": "Punjab",
    "Bhimbar": "Azad Jammu & Kashmir",
    "Buni": "Khyber Pakhtunkhwa",
    "Bunji": "Gilgit-Baltistan",
    "Cantonment": "Punjab",
    "Chak Five Hundred Seventy-five": "Punjab",
    "Chak Forty-one": "Punjab",
    "Chak Jhumra": "Punjab",
    "Chak Sixty-one Gugera Branch": "Punjab",
    "Chak Thathi": "Punjab",
    "Chak Thirty-six North Branch": "Punjab",
    "Chakdarra": "Khyber Pakhtunkhwa",
    "Charbagh": "Khyber Pakhtunkhwa",
    "Charsadda": "Khyber Pakhtunkhwa",
    "Chauk Azam": "Punjab",
    "Chenab Nagar": "Punjab",
    "Chilas": "Gilgit-Baltistan",
    "Chishtian": "Punjab",
    "Chitral": "Khyber Pakhtunkhwa",
    "Choa Saidan Shah": "Punjab",
    "Chunian": "Punjab",
    "Dadu": "Sindh",
    "Dainyor": "Gilgit-Baltistan",
    "Dera Allahyar": "Balochistan",
    "Dhanot": "Punjab",
    "Dina": "Punjab",
    "Dinga": "Punjab",
    "Dipalpur": "Punjab",
    "Doaba": "Khyber Pakhtunkhwa",
    "Drazinda": "Punjab",
    "Dulmial": "Punjab",
    "Eminabad": "Punjab",
    "Faruka": "Punjab",
    "Firoza": "Punjab",
    "Gadani": "Balochistan",
    "Gahi Mammar": "Punjab",
    "Gakuch": "Gilgit-Baltistan",
    "Ghora Gali": "Punjab",
    "Ghota Fatehgarh": "Punjab",
    "Ghotki": "Sindh",
    "Ghuenke": "Punjab",
    "Gilgit": "Gilgit-Baltistan",
    "Goth Tando Sumro": "Sindh",
    "Gujar Khan": "Punjab",
    "Gujrat": "Punjab",
    "Hadali": "Punjab",
    "Haider Khel": "Khyber Pakhtunkhwa",
    "Haji Shah": "Punjab",
    "Hajira": "Azad Jammu & Kashmir",
    "Hala": "Sindh",
    "Hangu": "Khyber Pakhtunkhwa",
    "Haripur": "Khyber Pakhtunkhwa",
    "Harnai": "Balochistan",
    "Harunabad": "Punjab",
    "Hasilpur": "Punjab",
    "Hassan Abdal": "Punjab",
    "Hattian Bala": "Azad Jammu & Kashmir",
    "Hujra Shah Muqim": "Punjab",
    "Idak": "Punjab",
    "Jacobabad": "Sindh",
    "Jaglot": "Gilgit-Baltistan",
    "Jalalabad": "Khyber Pakhtunkhwa",
    "Jalalpur Bhattian": "Punjab",
    "Jalalpur Jattan": "Punjab",
    "Jamshoro": "Sindh",
    "Jandola": "Khyber Pakhtunkhwa",
    "Jaranwala": "Punjab",
    "Jauharabad": "Punjab",
    "Jhang City": "Punjab",
    "Johi": "Sindh",
    "Kabirwala": "Punjab",
    "Kahan": "Balochistan",
    "Kahror Pakka": "Punjab",
    "Kalat": "Balochistan",
    "Kalu Khan": "Khyber Pakhtunkhwa",
    "Kamalia": "Punjab",
    "Kambar": "Sindh",
    "Kandhkot": "Sindh",
    "Karak": "Khyber Pakhtunkhwa",
    "Kathri": "Sindh",
    "Khairpur Mir’s": "Sindh",
    "Khairpur Tamewah": "Punjab",
    "Khanewal": "Punjab",
    "Khanpur": "Punjab",
    "Khapalu": "Gilgit-Baltistan",
    "Kharan": "Balochistan",
    "Kharian": "Punjab",
    "Khewra": "Punjab",
    "Khipro": "Sindh",
    "Khushab": "Punjab",
    "Khuzdar": "Balochistan",
    "Khwazakhela": "Khyber Pakhtunkhwa",
    "Kot Addu": "Punjab",
    "Kot Mumin": "Punjab",
    "Kot Radha Kishan": "Punjab",
    "Kotla Qasim Khan": "Punjab",
    "Kotli": "Azad Jammu & Kashmir",
    "Kotri": "Sindh",
    "Kuchlagh": "Balochistan",
    "Kulachi": "Khyber Pakhtunkhwa",
    "Kundian": "Punjab",
    "Lala Musa": "Punjab",
    "Lalian": "Punjab",
    "Landi Kotal": "Khyber Pakhtunkhwa",
    "Liaquatpur": "Punjab",
    "Lodhran": "Punjab",
    "Malak Abad": "Punjab",
    "Malakwal": "Punjab",
    "Mandi Burewala": "Punjab",
    "Mankera": "Punjab",
    "Mansehra": "Khyber Pakhtunkhwa",
    "Masho Khel": "Khyber Pakhtunkhwa",
    "Mehrabpur": "Sindh",
    "Mian Channun": "Punjab",
    "Mian Sahib": "Punjab",
    "Mianwali": "Punjab",
    "Mingaora": "Khyber Pakhtunkhwa",
    "Miro Khan": "Sindh",
    "Mirpur Bhtoro": "Sindh",
    "Mirpur Mathelo": "Sindh",
    "Mithi": "Sindh",
    "Muridke": "Punjab",
    "Murree": "Punjab",
    "Nasatta": "Sindh",
    "Naushahro Firoz": "Sindh",
    "Nawan Shahr": "Punjab",
    "New Mirpur": "Azad Jammu & Kashmir",
    "Nurkot": "Sindh",
    "Pakpattan": "Punjab",
    "Panjgur": "Balochistan",
    "Parachinar": "Khyber Pakhtunkhwa",
    "Pasni": "Balochistan",
    "Pasrur": "Punjab",
    "Pattoki": "Punjab",
    "Phalia": "Punjab",
    "Phularwan": "Punjab",
    "Pind Dadan Khan": "Punjab",
    "Pindi Bhattian": "Punjab",
    "Pishin": "Balochistan",
    "Qazi Ahmad": "Punjab",
    "Rangewala": "Punjab",
    "Ranipur": "Sindh",
    "Ratodero": "Sindh",
    "Renala Khurd": "Punjab",
    "Risalpur Cantonment": "Khyber Pakhtunkhwa",
    "Rohri": "Sindh",
    "Roulia": "Punjab",
    "Rukan": "Punjab",
    "Sadda": "Khyber Pakhtunkhwa",
    "Saddiqabad": "Punjab",
    "Safdarabad": "Punjab",
    "Saidpur": "Punjab",
    "Saidu Sharif": "Khyber Pakhtunkhwa",
    "Sakrand": "Sindh",
    "Sambrial": "Punjab",
    "Samundri": "Punjab",
    "Sanghar": "Sindh",
    "Sangota": "Khyber Pakhtunkhwa",
    "Sarai Alamgir": "Punjab",
    "Sargodha": "Punjab",
    "Sarhari": "Punjab",
    "Shabqadar": "Khyber Pakhtunkhwa",
    "Shah Latif Town": "Sindh",
    "Shahdadpur": "Sindh",
    "Shakargarh": "Punjab",
    "Shergarh": "Punjab",
    "Shujaabad": "Punjab",
    "Sialkot City": "Punjab",
    "Sillanwali": "Punjab",
    "Skardu": "Gilgit-Baltistan",
    "Sukheke Mandi": "Punjab",
    "Sultanpur Mor": "Sindh",
    "Surab": "Balochistan",
    "Surmon Chogga Grong": "Punjab",
    "Talamba": "Punjab",
    "Talhar": "Sindh",
    "Tando Allahyar": "Sindh",
    "Tando Muhammad Khan": "Sindh",
    "Tank": "Khyber Pakhtunkhwa",
    "Taxila": "Punjab",
    "Thal": "Punjab",
    "Thari Mir Wah": "Sindh",
    "Thatta": "Sindh",
    "Timargara": "Khyber Pakhtunkhwa",
    "Toba Tek Singh": "Punjab",
    "Uch Sharif": "Punjab",
    "Umarkot": "Sindh",
    "Usta Muhammad": "Balochistan",
    "Uthal": "Balochistan",
    "Vihari": "Punjab",
    "Wadala Sandhuan": "Punjab",
    "Wahga": "Punjab",
    "Wazirabad": "Punjab",
    "Zafarwal": "Punjab",
    "Zhob": "Balochistan",
    "Ziarat": "Balochistan"
};